name:  Run tests, build and push Docker image for run housing price predictions

on:
  push:
    branches:
      - '*' # run for all branches without / in the name
  release:
    types:
      - published
      - edited

jobs:
  # Run code tests before building the image, to ensure it is good to go
  build:
    name: Run code tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2 # checkout the repository so workflow can access it
    - name: Setting up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2 # set up python environment for use in actions
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with unittest
      run: |
        python -m unittest discover

  push_to_registry:
    name: Build and push Docker image to Docker Hub
    if: github.event_name == 'release' # only when a "release" is "published"
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: carolgonz/house-prince-predictions:latest